//Conversations
export const FETCH_CONVERSATIONS = "FETCH_CONVERSATIONS";
export const UPDATE_RECENT_SENDERS = "UPDATE_RECENT_SENDERS";
export const UPDATE_CONVERSATIONS = "UPDATE_CONVERSATIONS";
export const UPDATE_CONVERSATIONS_LIST_HAS_MORE =
  "UPDATE_CONVERSATIONS_LIST_HAS_MORE";
export const LOADING_CONVERSATIONS = "LOADING_CONVERSATIONS";

//Chats
export const FETCH_USER_CHATS = "FETCH_USER_CHATS";
export const UPDATE_USER_CHATS = "UPDATE_USER_CHATS";
export const SEND_CHAT = "SEND_CHAT";

//Contacts
export const FETCH_CONTACTS = "FETCH_CONTACTS";
export const SAVE_CONTACT = "SAVE_CONTACT";
export const UPDATE_CONTACT = "UPDATE_CONTACT";
export const DELETE_CONTACT = "DELETE_CONTACT";

//Employee
export const AUTH_EMPLOYEE = "AUTH_EMPLOYEE";

//Notifications
export const GENERAL_ERROR_MESSAGE = "GENERAL_ERROR_MESSAGE";
export const GENERAL_SUCCESS_MESSAGE = "GENERAL_SUCCESS_MESSAGE";
